version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: table_reservation_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rootpassword
      # We will use Prisma later to create the logical user_db, booking_db, billing_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: table_reservation_es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disabled for local MVP development
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: table_reservation_rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port (Browser dashboard)

volumes:
  postgres_data:
  es_data: